import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// import Header from './(client)/components/Header';
// import Footer from './(client)/components/Footer';
// import {ErrorWrapper} from './(client)/error-wrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "NextJs Tutorial - Codevelution",
    template: "%s | Condevolution",
    absolute: ""
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased w-360 ml-auto mr-auto`}
    >
      <body className="min-h-full flex flex-col">
        {/* <Header />
          <ErrorWrapper>
            
          </ErrorWrapper>
        <Footer /> */}
        {children}
      </body>
    </html>
  );
}
